version: '3'
services:
  db:
    hostname: todo-db
    image: postgres:13.4-alpine3.14
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build:
      dockerfile: ./docker/web/Dockerfile
      context: .
    volumes:
      - .:/app:cached
    environment:
      - DATABASE_URL=postgresql://postgres:password@todo-db/app_development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - live-backend
  redis:
    image: redis:6-alpine3.13
  live-backend:
    build:
      dockerfile: ./docker/live_backend/Dockerfile
      context: .
    volumes:
      - .:/app:cached
    depends_on:
      - redis
    ports:
      - "3002:3001"

volumes:
  database_data:
