apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-handler
  labels:
    app.kubernetes.io/name: async-handler
spec:
  replicas: {{ .Values.asyncHandler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: async-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: async-handler
    spec:
      containers:
        - name: async-handler
          image: raftt/demo-async-handler
          env:
            - name: DATABASE_URL
              value: {{ .Values.postgresUrl }}
            - name: KAFKA_BOOTSTRAP_SERVER
              value: {{ .Values.kafkaBroker }}
      initContainers:
{{ if .Values.postgres.enable }}
        - name: init-db
          image: {{ .Values.postgres.image }}
          command: [ 'sh', '-c', "until pg_isready -d $DATABASE_URL; do echo waiting for db; sleep 1; done" ]
          env:
            - name: DATABASE_URL
              value: {{ .Values.postgresUrl }}
{{ end }}
{{ if .Values.kafka.enable }}
        - name: init-kafka
          image: {{ .Values.kafka.kcat.image }}:{{ .Values.kafka.tag }}
          command: [ 'sh', '-c', "until kcat -b $KAFKA_BOOTSTRAP_SERVER -L; do echo waiting for kafka; sleep 1; done" ]
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: {{ .Values.kafkaBroker }}
{{ end }}
