apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-backend
  labels:
    app.kubernetes.io/name: live-backend
spec:
  replicas: {{ .Values.liveBackend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: live-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: live-backend
    spec:
      containers:
        - name: live-backend
          image: raftt/demo-live-backend
          env:
            - name: REDIS_URL
              value: {{ .Values.redisUrl }}
