apiVersion: v1
kind: Service
metadata:
  name: live-backend
  labels:
    app.kubernetes.io/name: live-backend
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app.kubernetes.io/name: live-backend
  type: ClusterIP
