{{ if .Values.redis.enable }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
  type: ClusterIP
  clusterIP: None
{{ end }}
