{{ if .Values.kafka.enable }}
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app.kubernetes.io/name: zookeeper
  type: ClusterIP
  clusterIP: None
{{ end }}
