web:
  replicas: 1
  postgresUrl: postgresql://postgres:password@todo-db/app_development

liveBackend:
  replicas: 1
  redisUrl: redis:6379

postgres:
  enable: true
  image: postgres:13.4-alpine3.14
  env:
    - name: POSTGRES_PASSWORD
      value: password

redis:
  enable: true
  image: redis:6-alpine3.13
